apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.artifactId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/source-location: url:https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
    backstage.io/techdocs-ref: url:https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
  tags:
    - java
    - quarkus
  links:
    - url: https://workspaces.openshift.com/#https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
      title: Openshift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  system: ${{ values.system }}
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  providedApis:
    - ${{values.artifactId | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.artifactId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  definition:
    $text: ./openapi.yaml