site_name: ${{values.name}}
site_description: ${{values.description}}
repo_url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Run you Quarkus service: quarkus-run.md